config:
    delay-between-messages: 1000
debug:
    enabled: false
zones:
    chat:
        enabled: true
        excluded-filters:
    signs:
        enabled: true
        excluded-filters:
            - duplicate-messages
            - leet
filters:
    duplicate-messages:
        default-level: 10
        priority: 5
    server-ip:
        default-level: 4
        priority: 1
    leet:
        default-level: 2
        priority: 4
    repeated-characters:
        default-level: 10
        priority: 2
        count: 5
    all-caps:
        default-level: 12
        priority: 3
    profanity:
        default-level: 10
        priority: 5
        whitelist:
            - "glass"
            - "assumption"
        templates:
            tmp1:
                expression: "\\b%FIRST+%REST+|%FIRST+%REST+\\b"
                default: true
        words:
            "fuck":
                level: 30
            "wank":
                level: 15
            "dick":
                level: 20
            "cock":
                level: 22
            "penis":
                level: 20
            "shit":
                level: 10
            "piss":
                level: 7
            "skeet":
                level: 13
            "bitch":
                level: 15
            "tits":
                level: 12
            "titties":
                level: 12
            "pussy":
                level: 20
            "cunt":
                level: 25
            "twat":
                level: 12
            "clit":
                level: 15
            "ass":
                level: 10
            "cum":
                level: 22
            "nigger":
                level: 30
            "nigga":
                level: 30
            "faggot":
                level: 25
            "queer":
                level: 25
            "slut":
                level: 15
            "anus":
                level: 15
            "arse":
                level: 15
